views/account_api.py
from flask import Blueprint, request, jsonify
from flask_sqlalchemy import SQLAlchemy
from database import db

from flask_login import login_user, logout_user, login_required, current_user
from auth import User

account_api = Blueprint("account_api", __name__)


@account_api.route("/login",methods=["POST"])
def login():
    data = request.get_json()
    rowdata = db.engine.execute("Select * from `Account_Manage`")
    for row in rowdata: #check account
        if row['account'] == data['account']:
            if row['password'] == data['password']:
                user = User(data['account'])
                login_user(user)
                return jsonify({'role':row['identity']}), 200
            else:
                return jsonify({"response":'password error'}), 400
    return jsonify({"response":"account not exist"}), 400

@account_api.route("/logout")
@login_required
def logout():
    logout_user()
    return jsonify({"response":''})

@account_api.route("/register",methods=["GET","POST"])
def register():
     if request.method == 'POST':
         try:
             role = -1 # 1:customer   3: restaurant
             data = request.get_json()
             rowdata = db.engine.execute("Select * from `Account_Manage`")
             print(data)
             for row in rowdata: #check account
                 if row['account'] == data['account']:
                     return jsonify({"response":'account has been used'}),400
             if data['role'] == 'customer':
                 role = 1
                 db.engine.execute("Insert Into `Account_Manage` values(%s,%s,%s)",\
                     (data["account"],data["password"],role))
                 db.engine.execute("Insert Into `Customer` values(%s,%s,%s,%s,%s)",\
                     (data["account"],data["username"],data["gender"],data["phone"],data["mail"]))
               
             if data['role'] == 'restaurant':
                 role = 3
                 print(data)
                 db.engine.execute("Insert Into `Account_Manage` values(%s,%s,%s)",\
                     (data["account"],data["password"],role))
                 db.engine.execute("Insert Into `Restaurant` values(%s,%s,%s,%s,%s,%s,%s)",\
                     (data["account"],data["username"],data['phone'],data['address'],\
                     data['menu'],data['status'],data["mail"]))
             return jsonify({"response":'success'}),200
         except:
             return jsonify({"response":'error'}),400

'''@account_api.route("/test")
def show_data():
    sql_cmd = """ select * from restaurant """
    query_data = db.engine.execute(sql_cmd)
    result = "Data: "
    for row in query_data:
        result += "<br />Name: " + row['name'] + "<br /> ID: "+row["account"] +"<br />"
    return result'''

views/account_web.py
from re import S
from flask import (
    Blueprint,
    request,
    jsonify,
    render_template,
    url_for,
    redirect,
    flash,
    make_response
)
from flask_sqlalchemy import SQLAlchemy
from database import db
from flask_login import login_user, current_user, logout_user, login_required

from auth import User
from lib.account import get_all_user

account_web = Blueprint("account_web", __name__)

@account_web.route("/login",methods=["GET"])
def login():
    return render_template("login.html", auth="none")
    """if not request.form["password"]:
        return render_template("login.html", auth="none")
    users = get_all_user()
    account = request.form["account"]
    if (account in users) and request.form['password'] == users[account]:
        user = User(account)
        login_user(user)
        flash(f"歡迎 {user}! 願你找到 Foodriend!")
        if current_user.identity == "restaurant":
            resp = make_response(render_template("order.html"))
            resp.set_cookie("samesite","Lax")
            return render_template("order.html")
        else:
            resp = make_response(render_template("group_list.html"))
            resp.set_cookie("samesite","Lax")
            return render_template("group_list.html", auth=current_user.identity)
    
    else:
        flash("login failed")
        return render_template("login.html", auth="none", Message="帳號或密碼輸入錯誤"), 400
    """

@account_web.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("account_web.login"))

@account_web.route("/register")
def register():
    return render_template("register.html", auth="none")
@account_web.route("/select_Role")
def select_Role():
    return render_template("select_Role.html",auth="none")

@account_web.route("/")
@login_required
def reroute():
		if current_user.identity == "supervisor":
				return redirect(url_for('supervisor_web.edit_page'))
		elif current_user.identity == "restaurant":
				return redirect(url_for('order_web.order_list'))
		else:
				return redirect(url_for('group_web.showGroup'))

views/group_web.py
from flask import (
    Blueprint,
    request,
    render_template,
    url_for,
    redirect,
    flash,
    json
)
from flask_sqlalchemy import SQLAlchemy
from database import db
from flask_login import login_user, current_user, logout_user, login_required

from auth import User
from lib.account import role, get_all_user
import views.customer_api as customer_usage


group_web = Blueprint("group_web", __name__)

@group_web.route("/list")
@login_required
def showGroup():
    result = "" 
    status = ""

    result, status = customer_usage.search(current_user.name)

    result = (json.loads(result.get_data().decode("utf-8")))[0]
   
    return render_template("group_list.html", user_info=result, auth=current_user.identity)

views/order_web.py
from flask import (
    Blueprint,
    render_template,
    url_for,
    json
)
from flask_login import login_user, current_user, login_required

from views.order_api import get_order 
from lib.account import role, get_all_user

order_web = Blueprint("order_web", __name__)

@order_web.route("/list")
@login_required
def order_list():
    result, status = get_order()
    if status == 400:
        return "API get failed"
    result = json.loads(result.get_data().decode("utf-8"))
    return render_template("order_list.html", orders=result)

templates/group.html
{% extends "layout.html" %}

{% block content %}			
<section class="contact section-show">
    <div class="container">
        <div class="section-title">
            <h2>Group</h2>
            <p>Group Page</p>
        </div>

        <!--
            add your code here!!
        -->
    </div>
</section>
{% endblock %}

templates/group_backup.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Group Page</title>
        <script type="text/javascript">
            function sendJSON() {
		var mainUser = document.getElementById('main_user').value;
		var numPeople = document.getElementById('num_people').value;
                var time = document.getElementById('time').value;
                var restaurant = document.getElementById('restaurant').value;
                var orderContent = document.getElementById('order_content').value;

                var xhr = new XMLHttpRequest();
                var url = "https://140.113.213.74/groups/";

                xhr.open("POST", url, true);

                xhr.setRequestHeader('Content-Type', 'application/json');

                var data = JSON.stringify({"main_user": mainUser, "num_people": numPeople,"time": time, "restaurant": restaurant, "order_content": orderContent});
		console.log(data);
                xhr.send(data);
            }
        </script>
    </head>
    <body>
        <h1> {{title}} </h1>
        <form method="post">
            <label for="main_user">Main user:</label>
            <input type="text" id="main_user" name="main_user"><br>
            <label for="num_people">Number of people:</label>
            <input type="text" id="num_people" name="num_people"><br>
            <label for="time">Time:</label>
            <input type="datetime" id="time" name="time"><br>
            <label for="restaurant">Restaurant:</label>
            <input type="text" id="restaurant" name="restaurant"><br>
            <label for="order_content">Order contents:</label>
            <input type="text" id="order_content" name="order_content"><br>
            <br>
            <button name="submit" id="submit" onclick="sendJSON()">submit</button>
        </form>
    </body>
</html>

templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width,initial-scale=1.0">
	<title>Fooriend</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <link rel="shortcut icon" href="#">
    <!-- <link rel="stylesheet" href="http:140.113.213.74:8888/static/assets/css/Personal/assets/vendor/bootstrap/css/bootstrap.min.css"> -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-1.10.2.js"></script>	

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    
    <link href="http://140.113.213.74:8888/static/assets/css/style.css" rel="stylesheet" >
    
    <link href="http://140.113.213.74:8888/static/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="http://140.113.213.74:8888/static/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="http://140.113.213.74:8888/static/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="http://140.113.213.74:8888/static/assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
    <link href="http://140.113.213.74:8888/static/assets/vendor/remixicon/remixicon.css" rel="stylesheet">
    <link href="http://140.113.213.74:8888/static/assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">

    {% block header %}
    {% endblock %}

</head>
<body>
    
    {% include 'navbar.html' %}
    
    {% block content %}
    {% endblock %}

    <div class="credits">
        Copyright &copy; 2021-2021 &mdash; 炫芬與他的快樂夥伴
    </div>
    
    <!-- JS Files -->
    <script src="http://140.113.213.74:8888/static/assets/vendor/purecounter/purecounter.js"></script>
    <script src="http://140.113.213.74:8888/static/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="http://140.113.213.74:8888/static/assets/vendor/glightbox/js/glightbox.min.js"></script>
    <script src="http://140.113.213.74:8888/static/assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
    <script src="http://140.113.213.74:8888/static/assets/vendor/swiper/swiper-bundle.min.js"></script>
    <script src="http://140.113.213.74:8888/static/assets/vendor/waypoints/noframework.waypoints.js"></script>
    <script src="http://140.113.213.74:8888/static/assets/vendor/php-email-form/validate.js"></script>

    <script src="http://140.113.213.74:8888/static/assets/js/main.js"></script>
    
</body>
</html>

templates/login.html
{% extends "layout.html" %}

{% block header %}
<!--<script src="{{ url_for('static',filename='account.js')}}"></script>-->

<script>
    $(document).ready(function(){
        $("#submit_btn").click(function(){
            var account = $("#account").val();
            var password = $("#password").val();
            $.ajax ({
                url: "https://140.113.213.74:8888{{url_for('account_api.login')}}",
                type: "POST",
                cache: false,
                dataType: "json",
                data : JSON.stringify({"account": account, "password": password }),
                contentType: "application/json",
                success: function(data, testStatus, xhr){
                    if(xhr.status == '200'){
                       window.location.replace("http://140.113.213.74:8888{{url_for('account_web.reroute')}}");
                    }
                },
                error: function(xhr, ajaxOptions, thrownError){
				if(xhr.status == "400"){
					alert("Incorrect accont or password");
			window.location.replace("http://140.113.213.74:8888{{url_for('account_web.login')}}");
				}
                }
            });
        });
    });
</script>
{% endblock %}

{% block content %} 
<section class="contact section-show">
    <div class="container">
        <div class="section-title">
            <h2>Login</h2>
            <p>登入</p>
        </div>

        <form id="login-form" class="info-box php-email-form mt-4">
            <div class="form-froup mt-3">
                <h3>帳號</h3>
                <input id="account" type="text" class="form-control" name="account" placeholder="Account" required>
            </div>
            <div class="form-froup mt-3">
                <h3>密碼</h3>
                <input id="password" type="password" class="form-control" name="password" placeholder="Password" required>
            </div>
            <br>
            <div class="text-center"><button type="submit" id="submit_btn">Login</button></div>
        </form>
    </div>
</section>
{% endblock %}

templates/navbar.html
<header id="header" class="header-top">
  <div class="container">
    <h1><a href="#">Fooriend</a></h1>

    <nav id="navbar" class="navbar">
      <ul>
        {% if auth == "none" %}
          <li><a class="nav-link" href="{{url_for('account_web.login')}}">登入</a></li>
          <li><a class="nav-link" href="{{url_for('account_web.select_Role')}}">註冊</a></li>
        {% else %}
          {% if current_user.identity=="customer" %}
	        <li><a class="nav-link" href="{{ url_for('group_web.showGroup')}}">Group</a></li>
          <li><a class="nav-link" href="{{ url_for('restaurant_web.showRestaurant')}}">Restaurant</a></li>
          <li><a class="nav-link" href="{{ url_for('order_web.order_list')}}">Order</a></li>
          <li><a class="nav-link" href="{{ url_for('profile_web.search_web', username= current_user.name) }}">Profile</a></li>
          {% elif current_user.identity=="restaurant"%}
	        <li><a class="nav-link" href="{{ url_for('profile_web.search_web', username=current_user.name)}}">Restaurant Info</a></li>
          <li><a class="nav-link" href="{{ url_for('order_web.order_list') }}">Order</a></li>
          {% endif %}
	        <li><a class="nav-link" href="{{ url_for('account_web.logout')}}">Logout</a></li>
        {% endif %}
      </ul>
      <i class="bi bi-list mobile-nav-toggle"></i>
    </nav>
  </div>
</header>

templates/order_list.html
{% extends "layout.html" %}

{% block header %}
{% if current_user.identity == "restaurant" %}
<script>
	function accept(ID){
		console.log(ID);
		var buttonID = "accept_btn_" + ID;
		var buttonText = "accept_" + ID;
		$.ajax({
			type:"POST",
			url: "http://140.113.213.74:8888/order/accept",
			data: JSON.stringify({"order_id":ID}),
			contentType: "application/json",
			success:function(data, testStatus, xhr){
				if(xhr.status=="200"){
					alert("accept order: " + ID);
					$("#accept_"+ID).text("accept");
					$("#accept_btn_"+ID).attr("disabled", true);
					//window.location.reload();
				}
				else if(xhr.status=="401"){
					alert("You don't have permission");
				}
			},
			error:function(xhr, ajaxOptions, thrownError){
				console.log(xhr.status);
				console.log(thrownError);
			}
		});
	}
</script>
{% endif %}
{% endblock %}

{% block content %}
<section class="contact section-show">
    <div class="container">
        <div class="section-title">
            <h2>Order</h2>
            <p>Order List</p>
        </div>
	<table id="order_list" class="table table-dark table-hover">
	    <thead>	
				<tr>
					<th>ID</th>
					<th>User</th>
					{% if current_user.identity == "customer"%}
					<th>Joined People</th>
					{% endif %}
					<th>Status</th>
					{% if current_user.identity == "customer"%}
					<th>Restaurant</th>
					{% endif %}
          <th>Detail</th>
          <th>Established time</th>
					{% if current_user.identity == "restaurant" %}
					<th>Accept</th>
					{% endif %}
				</tr>
			</thead>	
			<tbody>
				{% for order in orders %}
					<tr>
							<td>{{ order.id }}</td>
							<td>{{ order.username }}</td>
              {% if current_user.identity == "customer" %}					
              <td>{{ order.joined_user }}</td>
              {% endif %}

              <td id="accept_{{order.id}}">{{ "accept" if order.is_accept==1 else "not accept" }}</td>
							{% if current_user.identity == "customer" %}
              <td>{{ order.restaurant }}</td>
              {% endif %}
              <td>{{ order.content }}</td>
              <td>{{ order.time }}</td>
							{% if current_user.identity == "restaurant" %}
								<td><button class="btn btn-outline-success" id="accept_btn_{{ order.id }}" onclick='accept({{ order.id }})' {{"disabled" if order.is_accept==1 else ""}}>ACCEPT</button></td>
							{% endif %}
					</tr>
				{% endfor %}
			</tbody>
	</table>
 </div>
</section>
{% endblock %}

templates/register.html
{% extends "layout.html" %}

{% block header %}
        <style type='text/css'>
            .text {
                height: 30px;
            }
        </style>
{% endblock %}

{% block content %}
    <section class="contact section-show">
        <div class="container">
            <div class="section-title">
                <h2>Register</h2>
                <p>註冊</p>
            </div>

            <form class="info-box php-email-form mt-4">
                <div class="form-froup mt-3">
                    <h3 for='account'>帳號</h3>
                    <input id="account" type="text" class="form-control" name="account" placeholder="Account">
                </div>
                <div class="form-froup mt-3">
                    <h3 for='password'>密碼</h3>
                    <input id="password" type="password" class="form-control" name="password" placeholder="Password">
                </div>
                <div class="form-froup mt-3">
                    <h3 for='username'>Name: </h3>
                    <input type='text' class='form-control' id='username' name='username' placeholder='Your name'>
                </div>
                <div class="form-froup mt-3">
                    <h3 for='phone'>Phone: </h3>
                    <input type='text' class='form-control' id='phone' name='phone' placeholder='Your phone'>
                </div>
                <div class="form-froup mt-3">
                    <h3 for='mail'>Mail: </h3>
                    <input type='text' class='form-control' id='mail' name='mail' placeholder='Your mail'>
                </div>
                <!-- <div class="form-froup mt-3">
                    <h3 for='identityDiv'>身分: </h3>
                    
                    <p for='customer'><input type='radio' id='customer' name='identity' value='customer' checked='checked'> Customer</p>
                    
                    <p for='restaurant'><input type='radio' id='restaurant' name='identity' value='restaurant'> Restaurant</p>
                </div> -->
                <div id='info_area' class="form-froup mt-3">
                    <h3 for='genderDiv'>Gender: </h3>
                    
                    <p for='male'><input type='radio' id='male' name='gender' value='male'> Male</p>
                    
                    <p for='female'><input type='radio' id='female' name='gender' value='female'> Female</p>
                </div>
                <div class="text-center"><button type="submit" id="finish">Submit</button></div>
            </form>
<!--
        <h1>註冊</h1>
        <form action='' method=''>
            <label for='account'>帳號: </label>
            <input type='text' class='text' id='account' name='account' placeholder='帳號'><br>
            <label for='password'>密碼: </label>
            <input type='password' class='text' id='password' name='password' placeholder='密碼'><br>
            <label for='username'>Name: </label>
            <input type='text' class='text' id='username' name='username' placeholder='Your name'><br>
            <label for='phone'>Phone: </label>
            <input type='text' class='text' id='phone' name='phone' placeholder='Your phone'><br>
            <label for='identityDiv'>身分:</label>
            <input type='radio' id='customer' name='identity' value='customer' checked='checked'>
            <label for='customer'>Customer</label>
            <input type='radio' id='restaurant' name='identity' value='restaurant'>
            <label for='restaurant'>Restaurant</label><br><br>
            <div id='info_area'>
                <label>Gender:</label>
                <input type='radio' id='male' name='gender' value='male'>
                <label for='male'>Male</label>
                <input type='radio' id='female' name='gender' value='female'>
                <label for='female'>Female</label><br><br>
            </div>
            <button id='finish' type='' onclick='sendJson()'>Submit</button>
        </form>
    -->
        </div>
    </section>
        
        <script type='text/javascript'>
            var identity = '';
            let info_area = document.querySelector('#info_area');
            $(document).ready(function(){
                var coo = document.cookie;
                var cname = 'role=';
                var ca = document.cookie.split(';');
                identity = ca[0].split('=')[1];
                switch (identity) {
                    case 'customer':
                        info_area.innerHTML = "<h3 for='genderDiv'>Gender: </h3><p for='male'><input type='radio' id='male' name='gender' value='male'> Male</p><p for='female'><input type='radio' id='female' name='gender' value='female'> Female</p>";
                        break;
                    case 'restaurant':
                        info_area.innerHTML = "<h3 for='address'>Address:</h3><input type='text' class='text' id='address' name='address' placeholder='Your address'><br><h3 for='menu'>Menu:</h3><input type='text' class='text' id='menu' name='menu' placeholder='Your menu link'><br><h3>Status:</h3><p for='open'><input type='radio' id='open' name='status' value='open'> Open</p><p for='close'><input type='radio' id='close' name='status' value='close'> Close</p>";
                        break;
                }
            });

            var url=location.href;
            if(url.indexOf('?')!=-1){
                var id="";
                var ary=url.split('?')[1].split('&');
                for(i=0;i<=ary.length-1;i++){
                    if(ary[i].split('=')[0]=='role'){
                        console.log(ary[i].split('=')[1]);
                    }
                }
            }

            $(document).ready(function() {
                $("#finish").click(function(){
                    var account = $("#account").val();
                    var password = $("#password").val();
                    //var identity= $('input[name="identity"]:checked').val();
                    alert(identity);
                    var username = $("#username").val();
                    var phone = $("#phone").val();
                    var mail = $("#mail").val();
                    var sta = '0';
                    if(identity == 'restaurant') {
                        var addr = $("#address").val();
                        var menu = $("#menu").val();
                        var status = $('input[name="status"]:checked').val();
                        if(status == 'open') {
                            sta = '1';
                        }
                        $.ajax ({
                            url: "https://140.113.213.74:8888{{url_for('account_api.register')}}",
                            type: "POST",
                            cache: false,
                            dataType: "json",
                            data: JSON.stringify({"role": identity, "account": account, "password": password, "username": username, "phone": phone, "mail": mail, "address": addr, "menu": menu, "status": sta}),
                            contentType: "application/json",
                            success: function(data, testStatus, xhr){
                                if(xhr.status == '200'){
                                    window.location.replace("https://140.113.213.74:8888{{url_for('account_web.login')}}");
                                }
                            },
                            error: function(xhr, ajaxOptions, thrownError){
                                if(xhr.status == '400'){
                                    //alert(identity+' '+account+' '+password+' '+username+' '+phone+' '+menu+' '+addr+' '+sta);
                                    alert(mail);
                                    alert("Register Failed !");
                                    window.location.replace("https://140.113.213.74:8888{{url_for('account_web.register')}}");
                                }
                            }
                        });
                    }
                    else {
                        var gender = $('input[name="gender"]:checked').val();
                        $.ajax ({
                            url: "https://140.113.213.74:8888{{url_for('account_api.register')}}",
                            type: "POST",
                            cache: false,
                            dataType: "json",
                            data: JSON.stringify({"role": identity, "account": account, "password": password, "username": username, "gender": gender, "phone": phone, "mail": mail}),
                            contentType: "application/json",
                            success: function(data, testStatus, xhr){
                                if(xhr.status == '200'){
                                    window.location.replace("https://140.113.213.74:8888{{url_for('account_web.login')}}");
                                }
                            },
                            error: function(xhr, ajaxOptions, thrownError){
                                //alert(identity + account + password + gender + phone);
                                alert(mail);
                                alert("Register Failed !");
                                window.location.replace("https://140.113.213.74:8888{{url_for('account_web.register')}}");
                            }
                        });
                    }
                });
            });

            // function sendJson() {
            //     var account = document.getElementById('account').value;
            //     var password = document.getElementById('password').value;
            //     var restaurant = document.getElementById('restaurant').checked;
            //     //alert(restaurant)
            //     var username = document.getElementById('username').value;
            //     var phone = document.getElementById('phone').value;
            //     var identity = 'customer';
            //     if (restaurant == true) {
            //         identity = 'restaurant';
            //         var address = document.getElementById('address').value;
            //         var menu = document.getElementById('menu').value;
            //         var status = document.getElementById('status').value;
            //         var data = JSON.stringify({'account':account, 'password':password, 'role':identity, 'username':username, 'phone':phone, 'address':address, 'menu':menu, 'status':status});
            //     }
            //     else {
            //         var gender = document.getElementById('gender').value;
            //         var data = JSON.stringify({'account':account, 'password':password, 'role':identity, 'username':username, 'phone':phone, 'gender':gender});
            //     }
            //     var xhr = new XMLHttpRequest();
            //     var url = "http://192.168.0.103/account/register";
		
		    //     alert(url);
            //     xhr.open('POST', url, true);

            //     xhr.setRequestHeader('Content-Type', 'application/json');

            //     xhr.send(data);
            // }
        </script>
{% endblock %}

templates/select_Role.html
{% extends "layout.html" %}

{% block header %}
{% endblock %}

{% block content %}
    <section class="services section-show">
        <div class="container">
            <div class="section-title">
                <h2>Register</h2>
                <p>註冊</p>
            </div>
            
            <div class="row">
                <div class="col-md-6" id='customer'>
                    <a href="https://id.nycu.edu.tw/o/authorize/?client_id=PDgwWhMDCNbeInYChAKg1OnTGs7Vr1J7Xzs3HpXm&response_type=code&scope=profile">
                        <div class="icon-box">
                            <div class="icon"><i class="bi bi-mortarboard"></i></div>
                            <h4>Customer</h4>
                            <p>If you are part of NYCU, register through NYCU OAuth.</p>
                        </div>
                    </a>
                </div>

                <div class="col-md-6" id='restaurant'>
                    <a href="{{url_for('account_web.register')}}">
                        <div class="icon-box">
                            <div class="icon"><i class="bi bi-bag-plus"></i></div>
                            <h4>Restaurant</h4>
                            <p>Others, register through our website.</p>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </section>
    <script type='text/javascript'>
        $("#customer").click(function() {
            var expires = new Date();
            expires.setTime(expires.getTime() + 60000); // 30 seconds
            document.cookie = "role=" + escape('customer') + ';expires=' + expires.toGMTString();
            //window.location.href = "https://140.113.213.74:8888{{url_for('account_web.register')}}";
        });

        $("#restaurant").click(function() {
            var expires = new Date();
            expires.setTime(expires.getTime() + 60000); // 30 seconds
            document.cookie = "role=" + escape('restaurant') + ';expires=' + expires.toGMTString();
            //window.location.href = "https://140.113.213.74:8888{{url_for('account_web.register')}}";
        });
    </script>
        
{% endblock %}